spring:
    application:
        name: mybatch
    config:
        import: optional:file:.env[.properties]
    datasource:
        jdbcUrl: jdbc:h2:mem:springdb;DB_CLOSE_DELAY=-1
        username: sa
        password: sa
        driver-class-name: org.h2.Driver
    h2:
        console:
            enabled: true
            path: /h2-console
    app:
        datasource:
            jdbcUrl: jdbc:mariadb://localhost:3306/mybatchdb
            username: mybatchuser
            password: mybatchpass
            driver-class-name: org.mariadb.jdbc.Driver
    batch:
        job:
            enabled: true
        jdbc:
            initialize-schema: always
